CREATE OR REPLACE FUNCTION usuario_dron(varchar)
    RETURNS TABLE(cliente varchar, id_dron varchar, dron_activo varchar)
	LANGUAGE PLPGSQL
    AS
$$
DECLARE
	usuario ALIAS FOR $1;
BEGIN
    RETURN query SELECT CLIENTE_NOMBREYAPELLIDO, DRON_ID AS DRON, DRON_NOMBRE AS DRON_ACTIVO
	FROM DRON 
	inner join CLIENTE
	ON CLIENTE.CLIENTE_ID = DRON.DR_CLIENTE_ID
	inner join DRON_HORA
	ON DRON.DRON_ID = DRON_HORA.DR_DRON_ID INNER JOIN HORA
	ON DRON_HORA.DR_HORA_ID = HORA.HORA_ID
	WHERE HORA_FIN - now()::TIME > '00:00' AND HORA_INICIO <= now()::TIME
	AND CLIENTE_NOMBREYAPELLIDO = usuario;
END;
$$


SELECT * FROM usuario_dron('Mia Anthonella Flores Ochoa')
