CREATE OR REPLACE FUNCTION DENEGAR_DRON()
  RETURNS TRIGGER 
  LANGUAGE PLPGSQL
  AS
$$
DECLARE
    reg RECORD;
BEGIN
	FOR reg IN SELECT * FROM DRON --CURSOR IMPLICITO  
	LOOP
		IF reg.DRON_CODIGO = NEW.DRON_CODIGO AND reg.DR_CLIENTE_ID <> NEW.DR_CLIENTE_ID THEN
			RAISE EXCEPTION 'No puedes contratar el dron: % porque ya tiene un cliente', new.DRON_CODIGO;
		END IF;
	END LOOP;
	RETURN NEW;
END;
$$


CREATE TRIGGER DENEGAR_DRON
  BEFORE INSERT
  ON DRON
  FOR EACH ROW
  EXECUTE PROCEDURE DENEGAR_DRON();
